"""empty message

Revision ID: d0a1d19f3408
Revises: 6e6321bc6c48
Create Date: 2023-02-26 14:09:17.473872

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d0a1d19f3408"
down_revision = "6e6321bc6c48"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_all4one_file", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), type_=sa.Uuid(), existing_nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_all4one_file", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.Uuid(), type_=sa.INTEGER(), existing_nullable=False
        )

    # ### end Alembic commands ###
